---
title: "Astral Treehouse Analysis/Trends"
author: "CaliSakuraium"
date: "November 8 2024"
format:
  html:
    code-fold: true
    code-tools: true
    df-print: paged
    code-line-numbers: true
    toc: true
editor: visual
execute:
  warning: false
  message: false
  keep-md: false
  echo: false
---

```{r, results='hide'}
#| label: load-packages
library(dplyr)
library(ggplot2)
library(ggthemes)
library(tidyverse)
library(tidyr)
library(readxl)
```

```{r, results='hide'}
#| label: activity_day_data
activity_day <- read_csv("data/activity_day.csv") |>
    mutate(date = as.Date(date, format = "%m/%d/%Y"))
```

```{r, results='hide'}
#| label: activity_day_graph
ggplot(
  activity_day,
  aes(x = date, y = messages)
) +
  geom_smooth(color="#D67FFF") +
  scale_x_date(
        limits = c(as.Date("2018-07-27"), as.Date("2024-10-31")),
        date_breaks = "3 months",
        date_labels = "%b %Y",
        expand = c(0, 0)
    ) +
    labs(
        title="Astral Treehouse Server Wide Activity",
        subtitle="From July 2018 to October 2024",
        x="Date",
        y="Messages"
    ) +
    theme(axis.text.x = element_text(angle = 90, hjust = 1, vjust = 0.5))
```

```{r, results='hide'}
#| label: activity_month_data
activity_month <- read_csv("data/activity_month.csv") |>
    pivot_longer(
        January:December,
        names_to="month",
        values_to="messages"
    )
```

```{r, results='hide'}
#| label: activity_month_graph
```